version: '3.4'

networks:
  dev:
    driver: bridge
    
    
services:
  delivery:
    image: docker.io/library/delivery
    container_name: delivery-services
    ports:
      - "8088:80"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings_ElephantSQL=Server=flora.db.elephantsql.com;Database=bggzbzsw;User Id=bggzbzsw;Password=7N68n99lNp-Hk68uNdO3r2UItR_oQsxy;
      - ASPNETCORE_URLS=http://+:80
    networks:
      - dev
      
volumes:
  app_data:
